descriptor-schema-version: "2.0"
 
info:
  name: Py_MQTT_SenseHat
  description: "Publish SenseHat sensor data"
  version: "1.4"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"
 
app:
  # Indicate app type (vm, paas, lxc etc.,)
  type: paas
 
  resources:
    profile: default 

    network:
      - 
        interface-name: eth0
        ports: 
            tcp: [6000]

  # Specify runtime and startup
  startup:
    runtime: python 
    runtime-version: 2.7.3
    target: start.sh 

